	<div id="banner" class="riferimenti">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h1>BLOCCO STIPENDI STATALI: AL VIA L'AZIONE COLLETTIVA DI CODACONS</h1>
				</div>
			</div>
		</div>
	</div>
	
	<div class="row spacer-50 hidden-xs"></div>
	<div class="row spacer-20 hidden-xs"></div>
	
	<div id="main">
		<div class="container">
			<div class="row"> <!-- main blocco 1 -->
				<div class="col-sm-6 riferimenti" id="main_left">
					<h3>Sentenza Corte Costituzionale n.178/2015</h3><br><br>				
					<p class="small text-center">REPUBBLICA ITALIANA<br>
						IN NOME DEL POPOLO ITALIANO<br><br>
						LA CORTE COSTITUZIONALE
					</p>
					<p class="small text-justify">
						composta dai signori: Presidente: Alessandro CRISCUOLO; Giudici : Paolo Maria NAPOLITANO, Paolo GROSSI, Giorgio LATTANZI, Aldo CAROSI, Marta CARTABIA, Mario Rosario MORELLI, Giancarlo CORAGGIO, Giuliano AMATO, Silvana SCIARRA, Daria de PRETIS, Nicolò ZANON,<br><br>
						ha pronunciato la seguente
					</p>
					<p class="small text-center">SENTENZA<br><br>[...]<br><br><em>ritenuto in fatto</em></p>
					<p class="small text-justify">
					    <span class="tabul"></span>1– ...I sindacati ricorrenti nel giudizio principale hanno chiesto di accertare il diritto a dar corso alle procedure contrattuali e negoziali, relative al triennio 2010-2012, per il personale di cui all’art. 2, comma 2, del decreto legislativo 30 marzo 2001, n. 165 (Norme generali sull’ordinamento del lavoro alle dipendenze delle amministrazioni pubbliche) e di condannare l’ARAN ad avviare le trattative per il rinnovo dei contratti, deducendo, a sostegno di tali domande, l’illegittimità costituzionale della normativa che “congela” i trattamenti economici percepiti dai dipendenti e “blocca” la contrattazione collettiva «con possibilità di proroga anche per l’anno 2014».<br>
						<span class="tabul"></span>...La sospensione della contrattazione sui trattamenti retributivi fino al 31 dicembre 2014 si accompagna all’impossibilità di qualsivoglia recupero, se solo si considera che, indipendentemente dalle ragioni poste a base della decretazione d’urgenza, si riscontra un prolungamento dei limiti posti all’autonomia collettiva.<br>
						<span class="tabul"></span>...Le disposizioni censurate, inoltre, si porrebbero in contrasto con l’art. 3, primo comma, Cost., anche in relazione all’art. 2 Cost. Le misure di risanamento sarebbero, infatti, destinate a ripercuotersi sulle retribuzioni dei soli pubblici dipendenti, così violando il principio di eguaglianza tra i cittadini e il dovere di solidarietà politica, sociale ed economica di cui agli artt. 3, primo comma, e 2 Cost.<br>
						<span class="tabul"></span>Tale dovere di solidarietà, difatti, non potrebbe non gravare sull’intera comunità.<br>
						<span class="tabul"></span>Il giudice a quo osserva che la sospensione delle procedure contrattuali riguardanti gli incrementi retributivi, protraendosi fino al 31 dicembre 2014, con esclusione di ogni possibilità di recupero e di ogni adeguamento dell’indennità di vacanza contrattuale, interrompe la dinamica retributiva, senza presentare quei caratteri di eccezionalità e di temporaneità che la Corte costituzionale ha ritenuto imprescindibili nel vagliare analoghe misure di contenimento della spesa pubblica.<br>
						<span class="tabul"></span>1.2– ...I sindacati intervenuti si dolgono del fatto che il legislatore abbia inibito del tutto alle organizzazioni sindacali la libertà di modulare la contrattazione nella materia retributiva, alla luce della situazione economica generale, così da impedire la ricerca di soluzioni volte a non far gravare i sacrifici sui lavoratori più deboli.<br>
						<span class="tabul"></span>A questa stregua, finanche i contratti collettivi dal contenuto prettamente normativo, che non incidono sulla spesa pubblica, sarebbero stati arbitrariamente preclusi.<br>
						<span class="tabul"></span>La disciplina, destinata a penalizzare in misura esorbitante il lavoro pubblico, sarebbe discriminatoria rispetto a quella applicabile al settore privato, non coinvolto da alcuna misura di contenimento delle retribuzioni, e lo sarebbe anche rispetto a quella che concerne il personale delle Forze armate, delle Forze di polizia e del Corpo nazionale dei vigili del fuoco, che beneficerebbe di assegni una tantum nel corso del triennio di blocco degli adeguamenti retributivi.<br>
						<span class="tabul"></span>1.3– ...La normativa, inoltre, contravverrebbe alla Carta sociale europea (art. 6, sul diritto di negoziazione collettiva), riveduta, con annesso, fatta a Strasburgo il 3 maggio 1996, ratificata e resa esecutiva con legge 9 febbraio 1999, n. 30, e agli artt. 27 e 28 della Carta dei diritti fondamentali dell’Unione europea, proclamata a Nizza il 7 dicembre 2000 e adattata a Strasburgo il 12 dicembre 2007, che tutelano, rispettivamente, il diritto dei lavoratori all’informazione e alla consultazione nell’àmbito dell’impresa e il diritto di negoziazione e di azioni collettive.<br>
						<span class="tabul"></span>...La norma impugnata istituirebbe, in spregio all’art. 53 Cost., un prelievo tributario e pregiudicherebbe il diritto dei lavoratori a percepire una retribuzione proporzionata alla quantità e alla qualità del lavoro svolto, violando, inoltre, i princípi di affidamento, di buona fede e di eguaglianza sostanziale.<br>
						<span class="tabul"></span>1.5– ...<br>
						<span class="tabul"></span>1.6– ...<br>
						<span class="tabul"></span>1.8– ...La contrattazione collettiva nel settore del lavoro pubblico, che può essere limitata in ragione di esigenze finanziarie di carattere generale e delle risorse concretamente disponibili (art. 47 del d.lgs. n. 165 del 2001), non dovrebbe essere sospesa per un periodo così lungo.<br>
						<span class="tabul"></span>Pur in assenza di risorse finanziarie, le parti collettive potrebbero operare interventi redistributivi e perequativi, per erogare tutela nei confronti delle fasce di lavoratori a più basso reddito.<br>
						<span class="tabul"></span>Per contro, in conseguenza delle misure impugnate, il peso del risanamento dei conti pubblici graverebbe in misura sproporzionata sulla sola categoria dei dipendenti pubblici.<br><br>
						<span class="tabul"></span>2– Con ordinanza depositata il 1° marzo 2014 e iscritta al n. 125 del registro ordinanze 2014, il Tribunale ordinario di Ravenna, in funzione di giudice del lavoro, ha sollevato questione di legittimità costituzionale dell’art. 9, commi 1, 2-bis, 17, primo periodo, e 21, ultimo periodo, del d.l. n. 78 del 2010 e dell’art. 16, comma 1, lettere b) e c), del d.l. n. 98 del 2011, in riferimento agli artt. 2, 3, primo comma, 35, primo comma, 36, primo comma, 39, primo comma, e 53 Cost.<br>
						<span class="tabul"></span>2.1– Il giudice rimettente espone di conoscere della controversia promossa da dipendenti del Ministero della giustizia, in servizio presso il Tribunale ordinario di Ravenna.<br>
						<span class="tabul"></span>I ricorrenti hanno chiesto, previo accertamento dell’illegittimità del blocco stipendiale e contrattuale, di vedere riconosciuto il diritto all’aumento e/o all’adeguamento del trattamento retributivo, fermo al 2010, e comunque il diritto all’indennizzo e/o all’indennità per il danno patito per effetto della violazione del diritto a una retribuzione giusta e proporzionata alla quantità e alla qualità del lavoro prestato o perlomeno adeguata all’inflazione e/o al costo della vita.<br>
						<span class="tabul"></span>Il lavoro – allegano i ricorrenti – si sarebbe aggravato in conseguenza della diminuzione del numero dei dipendenti dell’Ufficio per il “blocco” legislativo del turn over.<br>
						<span class="tabul"></span>La controversia è stata incardinata dinanzi al Tribunale di Ravenna anche dalla CONFSAL-UNSA, Confederazione generale dei sindacati autonomi dei lavoratori – Unione nazionale sindacati autonomi. In qualità di sindacato maggiormente rappresentativo del comparto Ministeri e di sindacato primo per rappresentatività del Ministero della giustizia, ha chiesto, in primo luogo, l’accertamento del diritto a partecipare alle procedure contrattuali collettive e, in secondo luogo, è intervenuta in senso adesivo alle ragioni dei propri iscritti.<br>
						<span class="tabul"></span>...Il blocco contrattuale sarebbe lesivo dei princípi consacrati dagli artt. 35, primo comma, e 39, primo comma, Cost., visto che andrebbe a detrimento dell’autonomia negoziale e della libertà sindacale riservata alle parti nell’àmbito della contrattazione collettiva.<br>
						<span class="tabul"></span>Gli interventi normativi, che limitano al 2013/2014 la riapertura delle procedure contrattuali soltanto per la parte normativa, non varrebbero a mutare il quadro appena delineato.<br>
						<span class="tabul"></span>2.2– ...<br>
						<span class="tabul"></span>2.3– ...Per quel che concerne il merito delle questioni, la difesa dello Stato ribadisce che le disposizioni censurate mirano a ridurre la spesa pubblica, in adempimento degli obblighi che derivano dall’appartenenza all’Unione europea e dell’obbligo, costituzionalmente sancito, di raggiungere l’equilibrio strutturale delle entrate e delle spese del bilancio.<br>
						<span class="tabul"></span>Sarebbe legittima, alla luce delle enunciazioni di principio della giurisprudenza costituzionale, l’introduzione di misure eccezionali, transitorie, non arbitrarie e consentanee allo scopo prefisso, volte a fissare limiti di compatibilità della contrattazione collettiva con le finanze pubbliche.<br>
						<span class="tabul"></span>Tali misure non sarebbero irragionevoli, in quanto salvaguarderebbero l’erogazione dell’indennità di vacanza contrattuale e non assoggetterebbero al vincolo né le componenti retributive legate ad eventi straordinari della dinamica retributiva individuale, né la parte accessoria variabile.<br>
						<span class="tabul"></span>Tali peculiarità garantirebbero il rispetto del principio di parità di trattamento, del vincolo sinallagmatico, tutelato dall’art. 36, primo comma, Cost., del diritto di azione sindacale e dell’autonomia negoziale, che non sarebbe stata affatto esclusa in radice, come dimostrerebbe l’esplicarsi della contrattazione integrativa e della contrattazione nazionale.<br>
						<span class="tabul"></span>2.4– ...<br>
						<span class="tabul"></span>2.5– ...<br>
						<span class="tabul"></span>Le parti intervenute lamentano che la normativa abbia bilanciato in maniera irragionevole e sproporzionata i diritti sociali fondamentali (artt. 35, primo comma, 36, primo comma, e 39, primo comma, Cost.) e gli obiettivi di pareggio di bilancio e di risanamento economico (art. 81 Cost.).<br>
						<span class="tabul"></span>La reiterazione delle misure, così come congegnata in questi anni, implicherebbe una deroga costante al meccanismo di adeguamento retributivo, pregiudizievole per i dipendenti che percepiscono una retribuzione modesta e sono costretti, in conseguenza del blocco del turn over, a un carico di lavoro superiore.<br><br>
						<span class="tabul"></span>3– All’udienza pubblica, le parti costituite nel giudizio e il Presidente del Consiglio dei ministri hanno insistito per l’accoglimento delle conclusioni formulate nelle difese scritte.
					</p>
					<p class="small text-center"><em>considerato in diritto</em></p>
					<p class="small text-justify">
						<span class="tabul"></span>1– ...La normativa impugnata, che determina per i lavoratori di cui all’art. 2, comma 2, del decreto legislativo 30 marzo 2001, n. 165 (Norme generali sull’ordinamento del lavoro alle dipendenze delle amministrazioni pubbliche) una prolungata sospensione delle procedure negoziali e dell’ordinaria dinamica retributiva, si porrebbe in contrasto con i princípi di eguaglianza, di tutela del lavoro, di proporzionalità della retribuzione al lavoro svolto, di libertà di contrattazione collettiva.<br>
						<span class="tabul"></span>Le limitazioni, imposte dal legislatore per il periodo 2010-2014, introdurrebbero una disciplina irragionevole e sproporzionata, discriminando, per un periodo tutt’altro che transitorio ed eccezionale, i lavoratori pubblici rispetto ai lavoratori del settore privato.<br>
						<span class="tabul"></span>2– ...Il giudice rimettente assume che il “congelamento” delle retribuzioni dei pubblici dipendenti rientranti nel regime della contrattazione collettiva, prolungatosi per il periodo 2010-2014, senza alcuna possibilità di recupero, riveli molteplici profili di contrasto con la Carta costituzionale.<br>
						<span class="tabul"></span>3– ...Alla sospensione delle «procedure contrattuali e negoziali» si associa la previsione del “congelamento” dei trattamenti retributivi, che, per gli anni 2011, 2012, 2013, non possono superare, neppure nelle componenti accessorie, «il trattamento ordinariamente spettante per l’anno 2010» (art. 9, comma 1).<br>
						<span class="tabul"></span>Anche il trattamento accessorio del personale, ivi compreso quello di livello dirigenziale, e il trattamento retributivo delle progressioni di carriera soggiacciono a limitazioni drastiche, che sono fatte segno delle specifiche censure del Tribunale ordinario di Ravenna.<br>
						<span class="tabul"></span>7– Le questioni di legittimità costituzionale devono essere esaminate alla stregua del quadro normativo appena delineato, caratterizzato da disposizioni susseguitesi nel tempo, legate da un evidente nesso di continuità, al fine di perseguire un dichiarato obiettivo di contenimento della spesa.<br>
						<span class="tabul"></span>7.1– La difesa dello Stato formula alcune eccezioni preliminari.<br>
						<span class="tabul"></span>Quanto al paventato difetto di incidentalità, si deve rilevare che entrambi i giudizi non si esauriscono nell’accertamento dell’illegittimità costituzionale della normativa censurata.<br>
						<span class="tabul"></span>Nel giudizio pendente dinanzi al Tribunale ordinario di Roma, le organizzazioni sindacali, oltre all’accertamento del diritto di accedere alla contrattazione collettiva, hanno chiesto la condanna dell’ARAN ad avviare le trattative. Nel contenzioso ravennate il giudice è investito delle questioni concernenti le pretese retributive dei lavoratori ricorrenti, nonché delle domande di natura indennitaria e risarcitoria.<br>
						<span class="tabul"></span>È palese l’interesse delle organizzazioni ricorrenti a reclamare l’effettiva tutela di prerogative costituzionali, ad esse riconoscibili, che si ritiene siano messe a repentaglio dalle norme impugnate.<br>
						<span class="tabul"></span>7.3– Nelle memorie integrative, depositate il 29 maggio 2015, la difesa dello Stato lamenta che i giudici rimettenti abbiano omesso di esplorare la praticabilità di un’interpretazione conforme al dettato costituzionale e di offrire una motivazione esaustiva sulla rilevanza della questione.<br>
						<span class="tabul"></span>Le ordinanze di rimessione superano, anche da tale angolo visuale, il vaglio di ammissibilità, sollecitato a questa Corte. Le censure di illegittimità costituzionale si appuntano contro una normativa con un significato letterale e sistematico inequivocabile, che non offre alcun appiglio ad una interpretazione alternativa, rispettosa dei princípi della Carta fondamentale.<br>
						<span class="tabul"></span>Le caratteristiche delle misure impugnate, che si traducono in un mero risparmio di spesa e non si atteggiano come decurtazione definitiva del patrimonio del soggetto passivo e come atto autoritativo di carattere ablatorio, diretto a reperire risorse per l’erario, divergono dagli elementi distintivi del prelievo tributario (fra le tante, sentenza n. 70 del 2015, punto 4. del Considerato in diritto).<br>
						<span class="tabul"></span>Gli elementi indefettibili della prestazione tributaria, enucleati dalla costante giurisprudenza di questa Corte, si identificano, per un verso, nella presenza di una disciplina legale, finalizzata in via prevalente a provocare una decurtazione patrimoniale del soggetto passivo, svincolata da ogni modificazione del rapporto sinallagmatico. Per altro verso, a definire la natura tributaria concorre l’elemento teleologico.<br>
						<span class="tabul"></span>In particolare, le risorse derivanti dal prelievo e connesse a un presupposto economicamente rilevante, idoneo a porsi come indice della capacità contributiva, devono essere destinate a «sovvenire le pubbliche spese» (sentenza n. 310 del 2013, punto 11. del Considerato in diritto). Caduta la premessa che si tratti di un tributo, anche le censure di violazione dell’art. 53 Cost. perdono consistenza.<br>
						<span class="tabul"></span>Il sistema della contrattazione collettiva nel lavoro pubblico, inteso nella sua interezza, contempla la pianificazione degli oneri connessi al suo svolgersi nel tempo, secondo un modello dinamico, «in coerenza con i parametri previsti dagli strumenti di programmazione e di bilancio di cui all’articolo 1-bis della legge 5 agosto 1978, n. 468, e successive modificazioni e integrazioni» (art. 48, comma 1, del d.lgs. n. 165 del 2001).<br>
						<span class="tabul"></span>11– Ciò posto, l’analisi deve muovere dalle disposizioni dell’art. 9 del d.l. n. 78 del 2010, che reca l’eloquente rubrica «Contenimento delle spese in materia di impiego pubblico» e, in ossequio a tale linea programmatica, preclude ogni incremento dei trattamenti economici complessivi dei singoli dipendenti per gli anni 2011, 2012, 2013 (comma 1), ogni efficacia economica delle progressioni di carriera (comma 21), e – per il periodo che dal 1° gennaio 2011 giunge fino al 31 dicembre 2013 – vieta ogni incremento dell’ammontare complessivo delle risorse destinate annualmente al trattamento accessorio del personale (comma 2-bis).<br>
						<span class="tabul"></span>La scelta di adottare disposizioni restrittive culmina nella sospensione dello svolgimento delle procedure “contrattuali e negoziali” per il triennio 2010-2012 (comma 17).<br>
						<span class="tabul"></span>Alla stregua di tali rilievi, questa Corte ha riconosciuto la ragionevolezza di un sistema di misure dotate di una proiezione strutturale, che esclude in radice ogni possibilità di recupero delle procedure negoziali per il periodo di riferimento (sentenza n. 189 del 2012, punto 4.1. del Considerato in diritto).<br>
						<span class="tabul"></span>La natura pluriennale delle politiche di bilancio, espressamente considerata nei precedenti citati, è speculare alla durata triennale delle tornate contrattuali, nei termini consacrati nell’ “Intesa per l’applicazione dell’Accordo quadro sulla riforma degli assetti contrattuali del 22 gennaio 2009 ai comparti contrattuali del settore pubblico”, siglata a Roma il 30 aprile 2009 dai ministri competenti e da alcune organizzazioni sindacali (si veda, in particolare, art. 2, lettera a).<br>
						<span class="tabul"></span>La ragionevolezza delle misure varate discende anche dalla particolare gravità della situazione economica e finanziaria, concomitante con l’intervento normativo.<br>
						<span class="tabul"></span>Tali dati contingenti sono confermati sia dalle fonti ufficiali (Rapporto semestrale ARAN sulle retribuzioni dei pubblici dipendenti, giugno 2010), sia dai lavori preparatori. Il dibattito che, al Senato, scandisce l’iter parlamentare della conversione in legge del decreto polarizza l’attenzione sulla «particolare gravità della situazione economica e finanziaria internazionale» e sulle «ripercussioni sull’economia nazionale» (seduta della Quinta Commissione del Senato – Commissione Bilancio – del 16 giugno 2010).<br>
						<span class="tabul"></span>Dal canto suo, la magistratura contabile avvalora l’urgenza di intervenire con misure di contenimento delle retribuzioni (Corte dei conti, sezioni riunite in sede di controllo, rapporto 2012 sul coordinamento della finanza pubblica, e Corte dei conti, sezioni riunite in sede di controllo, rapporto 2011 sul coordinamento della finanza pubblica).<br>
						<span class="tabul"></span>La ragionevolezza dell’intero impianto normativo si coglie anche nell’incidenza delle misure su una dinamica retributiva pubblica, che si attestava «su valori più sostenuti di quanto registrato nei settori privati dell’economia» (si veda il citato Rapporto semestrale ARAN, giugno 2010). Nella seduta della Quinta Commissione del Senato (Commissione Bilancio), tenutasi il 16 giugno 2010, si è sottolineato che nell’ultimo decennio le retribuzioni dei dipendenti pubblici hanno visto «un incremento di fatto sensibilmente superiore per la pubblica amministrazione rispetto a quello degli altri due comparti» dell’industria e dei servizi di mercato. Tale dato collima con quanto è stato segnalato dalla Corte dei conti, sezioni riunite di controllo, nel rapporto 2012 sul coordinamento della finanza pubblica.<br>
						<span class="tabul"></span>Il carattere generale delle misure varate dal d.l. n. 78 del 2010, inserite in un disegno organico improntato a una dimensione programmatica, scandita su un periodo triennale, risponde all’esigenza di governare una voce rilevante della spesa pubblica, che aveva registrato una crescita incontrollata, sopravanzando l’incremento delle retribuzioni del settore privato.<br>
						<span class="tabul"></span>Sono dunque da disattendere le censure di violazione degli artt. 36, primo comma, e 39, primo comma, Cost., in quanto il sacrificio del diritto alla retribuzione commisurata al lavoro svolto e del diritto di accedere alla contrattazione collettiva non è, nel quadro ora delineato, né irragionevole né sproporzionato.<br>
						<span class="tabul"></span>...L’argomento suggestivo del “blocco” del turn over, legato alla specificità del settore della giustizia e della realtà locale, analizzata nella predetta ordinanza di rimessione, non vale a dar conto della violazione dei precetti costituzionali denunciata in capo a una normativa destinata ad applicarsi – nella sua valenza generale ed astratta – a una platea più vasta di dipendenti del settore pubblico.<br>
						<span class="tabul"></span>Peraltro, dall’incremento delle pendenze da trattare, congiunto con l’assottigliarsi del numero dei dipendenti, non si può inferire, per ciò stesso, un aumento del carico di lavoro, che renda radicalmente sproporzionata la retribuzione percepita.<br>
						<span class="tabul"></span>...La contrattazione deve potersi esprimere nella sua pienezza su ogni aspetto riguardante la determinazione delle condizioni di lavoro, che attengono immancabilmente anche alla parte qualificante dei profili economici.<br>
						<span class="tabul"></span>Non appaiono decisivi, per escludere il contrasto con l’art. 39, primo comma, Cost., i molteplici contratti enumerati dalla difesa dello Stato, che non attestano alcun superamento della sospensione delle procedure negoziali per la parte squisitamente economica del rapporto di lavoro e per gli aspetti più caratteristici di tale àmbito.<br>
						<span class="tabul"></span>L’estensione fino al 2015 delle misure che inibiscono la contrattazione economica e che, già per il 2013-2014, erano state definite eccezionali, svela, al contrario, un assetto durevole di proroghe. In ragione di una vocazione che mira a rendere strutturale il regime del “blocco”, si fa sempre più evidente che lo stesso si pone di per sé in contrasto con il principio di libertà sindacale sancito dall’art. 39, primo comma, Cost.<br>
						<span class="tabul"></span>16– La libertà sindacale è tutelata dall’art. 39, primo comma, Cost., nella sua duplice valenza individuale e collettiva, e ha il suo necessario complemento nell’autonomia negoziale (ex plurimis, sentenze n. 697 del 1988, punto 3. del Considerato in diritto, e n. 34 del 1985, punto 4. del Considerato in diritto).<br>
						<span class="tabul"></span>...Il «diritto di negoziare e di concludere contratti collettivi» è riconosciuto anche dall’art. 28 della Carta dei diritti fondamentali dell’Unione europea, proclamata a Nizza il 7 dicembre 2000 e adattata a Strasburgo il 12 dicembre 2007, che ha ora «lo stesso valore giuridico dei trattati», in forza dell’art. 6, comma 1, del Trattato sull’Unione europea (TUE), come modificato dal Trattato di Lisbona, firmato il 13 dicembre 2007, ratificato e reso esecutivo con legge 2 agosto 2008 n. 130, ed entrato in vigore il 1° dicembre 2009.<br>
						<span class="tabul"></span>Infine, in un quadro inteso a riconoscere e a promuovere il ruolo delle parti sociali, a favorire il dialogo tra le stesse, nel rispetto della loro autonomia, si deve ricordare l’art. 152, comma 1, del Trattato sul funzionamento dell’Unione europea (TFUE), norma introdotta con il Trattato di Lisbona.<br>
						<span class="tabul"></span>17– Il reiterato protrarsi della sospensione delle procedure di contrattazione economica altera la dinamica negoziale in un settore che al contratto collettivo assegna un ruolo centrale (sentenza n. 309 del 1997, punti 2.2.2., 2.2.3. e 2.2.4. del Considerato in diritto). Nei limiti tracciati dalle disposizioni imperative della legge (art. 2, commi 2, secondo periodo, e 3-bis del d.lgs. n. 165 del 2001), il contratto collettivo si atteggia come imprescindibile fonte, che disciplina anche il trattamento economico (art. 2, comma 3, del d.lgs. n. 165 del 2001), nelle sue componenti fondamentali ed accessorie (art. 45, comma 1, del d.lgs. n. 165 del 2001), e «i diritti e gli obblighi direttamente pertinenti al rapporto di lavoro, nonché le materie relative alle relazioni sindacali» (art. 40, comma 1, primo periodo, del d.lgs. n. 165 del 2001).<br>
						<span class="tabul"></span>In una costante dialettica con la legge, chiamata nel volgere degli anni a disciplinare aspetti sempre più puntuali (art. 40, comma 1, secondo e terzo periodo, del d.lgs. n. 165 del 2001), il contratto collettivo contempera in maniera efficace e trasparente gli interessi contrapposti delle parti e concorre a dare concreta attuazione al principio di proporzionalità della retribuzione, ponendosi, per un verso, come strumento di garanzia della parità di trattamento dei lavoratori (art. 45, comma 2, del d.lgs. n. 165 del 2001) e, per altro verso, come fattore propulsivo della produttività e del merito (art. 45, comma 3, del d.lgs. 165 del 2001).<br>
						<span class="tabul"></span>Il contratto collettivo che disciplina il lavoro alle dipendenze delle pubbliche amministrazioni si ispira, proprio per queste peculiari caratteristiche che ne garantiscono l’efficacia soggettiva generalizzata, ai doveri di solidarietà fondati sull’art. 2 Cost.<br>
						<span class="tabul"></span>Tali elementi danno conto sia delle molteplici funzioni che, nel lavoro pubblico, la contrattazione collettiva riveste, coinvolgendo una complessa trama di valori costituzionali (artt. 2, 3, 36, 39 e 97 Cost.), in un quadro di tutele che si è visto essere presidiato anche da numerose fonti sovranazionali, sia delle disarmonie e delle criticità, che una protratta sospensione della dinamica negoziale rischia di produrre.<br>
						<span class="tabul"></span>Se i periodi di sospensione delle procedure “negoziali e contrattuali” non possono essere ancorati al rigido termine di un anno, individuato dalla giurisprudenza di questa Corte in relazione a misure diverse e a un diverso contesto di emergenza (sentenza n. 245 del 1997, ordinanza n. 299 del 1999), è parimenti innegabile che tali periodi debbano essere comunque definiti e non possano essere protratti ad libitum.<br>
						<span class="tabul"></span>Su tale linea converge anche la Corte europea dei diritti dell’uomo, che ha sottolineato l’esigenza di «un “giusto equilibrio” tra le esigenze di interesse generale della comunità e i requisiti di protezione dei diritti fondamentali dell’individuo» e ha salvaguardato le misure adottate dal legislatore portoghese – in tema di riduzione dei trattamenti pensionistici – sulla scorta dell’elemento chiave del limite temporale che le contraddistingue (Seconda sezione, sentenza 8 ottobre 2013, António Augusto da Conceiçao Mateus e Lino Jesus Santos Januário contro Portogallo, punti 23 e seguenti del Considerato in diritto).<br>
						<span class="tabul"></span>Il carattere ormai sistematico di tale sospensione sconfina, dunque, in un bilanciamento irragionevole tra libertà sindacale (art. 39, primo comma, Cost.), indissolubilmente connessa con altri valori di rilievo costituzionale e già vincolata da limiti normativi e da controlli contabili penetranti (artt. 47 e 48 del d.lgs. n. 165 del 2001), ed esigenze di razionale distribuzione delle risorse e controllo della spesa, all’interno di una coerente programmazione finanziaria (art. 81, primo comma, Cost.).<br>
						<span class="tabul"></span>Il sacrificio del diritto fondamentale tutelato dall’art. 39 Cost., proprio per questo, non è più tollerabile.<br>
						<span class="tabul"></span>Solo ora si è palesata appieno la natura strutturale della sospensione della contrattazione e può, pertanto, considerarsi verificata la sopravvenuta illegittimità costituzionale, che spiega i suoi effetti a séguito della pubblicazione di questa sentenza.<br>
						<span class="tabul"></span>18– Rimossi, per il futuro, i limiti che si frappongono allo svolgimento delle procedure negoziali riguardanti la parte economica, sarà compito del legislatore dare nuovo impulso all’ordinaria dialettica contrattuale, scegliendo i modi e le forme che meglio ne rispecchino la natura, disgiunta da ogni vincolo di risultato.<br>
						<span class="tabul"></span>Il carattere essenzialmente dinamico e procedurale della contrattazione collettiva non può che essere ridefinito dal legislatore, nel rispetto dei vincoli di spesa, lasciando impregiudicati, per il periodo già trascorso, gli effetti economici derivanti dalla disciplina esaminata.
					</p>
					<br><br>
					<p class="small text-center">PER QUESTI MOTIVI<br>
						<strong>LA CORTE COSTITUZIONALE</strong>
					</p>
					<p class="small text-justify">
						<span class="tabul"></span>riuniti i giudizi,<br><br>
						<span class="tabul"></span>1) dichiara l’illegittimità costituzionale sopravvenuta, a decorrere dal giorno successivo alla pubblicazione di questa sentenza nella Gazzetta Ufficiale della Repubblica e nei termini indicati in motivazione, del regime di sospensione della contrattazione collettiva, risultante da: art. 16, comma 1, lettera b), del decreto-legge 6 luglio 2011, n. 98 (Disposizioni urgenti per la stabilizzazione finanziaria), convertito, con modificazioni, dall’art. 1, comma 1, della legge 15 luglio 2011, n. 111, come specificato dall’art. 1, comma 1, lettera c), primo periodo, del d.P.R. 4 settembre 2013, n. 122 (Regolamento in materia di proroga del blocco della contrattazione e degli automatismi stipendiali per i pubblici dipendenti, a norma dell’articolo 16, commi 1, 2 e 3, del decreto-legge 6 luglio 2011, n. 98, convertito, con modificazioni, dalla legge 15 luglio 2011, n. 111); art. 1, comma 453, della legge 27 dicembre 2013, n. 147 (Disposizioni per la formazione del bilancio annuale e pluriennale dello Stato – Legge di stabilità 2014) e art. 1, comma 254, della legge 23 dicembre 2014, n. 190 (Disposizioni per la formazione del bilancio annuale e pluriennale dello Stato – Legge di stabilità 2015);<br>
						<span class="tabul"></span>2) dichiara inammissibili le questioni di legittimità costituzionale dell’art. 16, comma 1, lettera c), del d.l. n. 98 del 2011, come specificato dall’art. 1, comma 1, lettera d), del d.P.R. n. 122 del 2013, e dall’art. 1, comma 452, della legge n. 147 del 2013, promosse, in riferimento all’art. 36, primo comma, della Costituzione, dal Tribunale ordinario di Roma, in funzione di giudice del lavoro, e dal Tribunale ordinario di Ravenna, in funzione di giudice del lavoro, con le ordinanze di rimessione indicate in epigrafe;<br>
						<span class="tabul"></span>3) dichiara inammissibili le questioni di legittimità costituzionale dell’art. 9, commi 1 e 17, primo periodo, del decreto-legge 31 maggio 2010, n. 78 (Misure urgenti in materia di stabilizzazione finanziaria e di competitività economica), convertito, con modificazioni, dall’art. 1, comma 1, della legge 30 luglio 2010, n. 122, e dell’art. 16, comma 1, lettera b), del d.l. n. 98 del 2011, come specificato dall’art. 1, comma 1, lettera a), primo periodo, del d.P.R. n. 122 del 2013, con riguardo alla limitazione dei trattamenti economici complessivi dei singoli dipendenti, e dall’art. 1, comma 1, lettera c), primo periodo, del d.P.R. n. 122 del 2013 e dall’art. 1, comma 453, della legge n. 147 del 2013, con riguardo alla sospensione delle procedure contrattuali e negoziali per la parte economica per il periodo 2013-2014, sollevate, in riferimento agli artt. 35, primo comma, e 53, primo e secondo comma, della Costituzione, dal Tribunale ordinario di Roma, in funzione di giudice del lavoro, con l’ordinanza di rimessione indicata in epigrafe;<br>
						<span class="tabul"></span>4) dichiara inammissibili le questioni di legittimità costituzionale degli artt. 9, commi 1, 2-bis, 17, primo periodo, e 21, ultimo periodo, del d.l. n. 78 del 2010, e 16, comma 1, lettera b), del d.l. n. 98 del 2011, come specificato dall’art. 1, comma 1, lettera a), primo periodo, del d.P.R. n. 122 del 2013, con riguardo alla limitazione dei trattamenti economici complessivi dei singoli dipendenti, del trattamento accessorio, degli effetti economici delle progressioni di carriera, dall’art. 1, comma 456, della legge n. 147 del 2013, con riguardo alla limitazione dei trattamenti accessori, dall’art. 1, comma 1, lettera c), primo periodo, del d.P.R. n. 122 del 2013 e dall’art. 1, comma 453, della legge n. 147 del 2013, con riguardo alla sospensione delle procedure contrattuali e negoziali per la parte economica per il periodo 2013-2014, promosse, in riferimento all’art. 35, primo comma, della Costituzione, dal Tribunale ordinario di Ravenna, in funzione di giudice del lavoro, con l’ordinanza di rimessione indicata in epigrafe;<br>
						<span class="tabul"></span>5) dichiara non fondate le questioni di legittimità costituzionale dell’art. 9, commi 1 e 17, primo periodo, del d.l. n. 78 del 2010, sollevate, in riferimento agli artt. 2, 3, primo comma, 36, primo comma, e 39, primo comma, della Costituzione, dal Tribunale ordinario di Roma, in funzione di giudice del lavoro, con l’ordinanza di rimessione indicata in epigrafe;<br>
						<span class="tabul"></span>6) dichiara non fondate le questioni di legittimità costituzionale dell’art. 16, comma 1, lettera b), del d.l. n. 98 del 2011, come specificato dall’art. 1, comma 1, lettera a), primo periodo, del d.P.R. n. 122 del 2013, con riguardo alla limitazione dei trattamenti economici complessivi dei singoli dipendenti, dall’art. 1, comma 1, lettera c), primo periodo, del d.P.R. n. 122 del 2013, e dall’art. 1, comma 453, della legge n. 147 del 2013, con riguardo alla sospensione delle procedure contrattuali e negoziali per la parte economica per il periodo 2013-2014, sollevate, in riferimento agli artt. 2, 3, primo comma, e 36, primo comma, della Costituzione, dal Tribunale ordinario di Roma, in funzione di giudice del lavoro, con l’ordinanza di rimessione indicata in epigrafe;<br>
						<span class="tabul"></span>7) dichiara non fondate le questioni di legittimità costituzionale dell’art. 9, commi 1, 2-bis, 17, primo periodo, e 21, ultimo periodo, del d.l. n. 78 del 2010, promosse, in riferimento agli artt. 2, 3, primo comma, 36, primo comma, 39, primo comma, e 53, primo e secondo comma, della Costituzione, dal Tribunale ordinario di Ravenna, in funzione di giudice del lavoro, con l’ordinanza di rimessione indicata in epigrafe;<br>
						<span class="tabul"></span>8) dichiara non fondate le questioni di legittimità costituzionale dell’art. 16, comma 1, lettera b), del d.l. n. 98 del 2011, come specificato dall’art. 1, comma 1, lettera a), primo periodo, del d.P.R. n. 122 del 2013, con riguardo alla limitazione dei trattamenti economici complessivi dei singoli dipendenti, del trattamento accessorio, degli effetti economici delle progressioni di carriera, dall’art. 1, comma 456, della legge n. 147 del 2013, con riguardo alla limitazione dei trattamenti accessori, dall’art. 1, comma 1, lettera c), primo periodo, del d.P.R. n. 122 del 2013, e dall’art. 1, comma 453, della legge n. 147 del 2013, con riguardo alla sospensione delle procedure contrattuali e negoziali per la parte economica per il periodo 2013-2014, promosse, in riferimento agli artt. 2, 3, primo comma, 36, primo comma, e 53, primo e secondo comma, della Costituzione, dal Tribunale ordinario di Ravenna, in funzione di giudice del lavoro, con l’ordinanza di rimessione indicata in epigrafe.<br><br>
						<span class="tabul"></span>Così deciso in Roma, nella sede della Corte costituzionale, Palazzo della Consulta, il 24 giugno 2015.
					</p>
					<p class="small"><u><a href="http://www.cortecostituzionale.it/actionSchedaPronuncia.do?anno=2015&numero=178" target="_blank">Leggi il testo integrale della sentenza</a></u> </p>
				</div>
				<div class="col-sm-6">
					<?php require_once ('templates/aderisci.php'); ?>
				</div>
			</div><!-- /main blocco 1 -->			
		</div>	
		
		<div class="row spacer-50"></div>
		<div class="row spacer-50"></div>
		<div class="row spacer-20"></div>
		<div class="row spacer-20"></div>
	</div>	